name: linter-test
run-name: ${{ github.actor }} is running GitHub Actions 🚀

on: [pull_request]

jobs:
    SB_Github_Stats:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
                  cache: "npm"

            - name: Install dependencies
              run: npm i --no-save

            - name: Run linter
              run: npm run lint

            - name: Run unit tests
              run: npm test
